apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dynamicmemories.sscargal.com
spec:
  group: sscargal.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                capacity:
                  type: string
                  pattern: '^([0-9]+)(Ki|Mi|Gi|Ti|Pi|Ei)?$'
  scope: Namespaced
  names:
    plural: dynamicmemories
    singular: dynamicmemory
    kind: DynamicMemory
    shortNames:
    - dmem