apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamic-memory-scheduler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamic-memory-scheduler
  template:
    metadata:
      labels:
        app: dynamic-memory-scheduler
    spec:
      serviceAccountName: dynamic-memory-controller
      containers:
      - name: scheduler
        image: your-registry/dynamic-memory-scheduler:latest
        args:
        - --config=/etc/kubernetes/scheduler-config.yaml
        volumeMounts:
        - name: scheduler-config
          mountPath: /etc/kubernetes/scheduler-config.yaml
          subPath: scheduler-config.yaml
      volumes:
      - name: scheduler-config
        configMap:
          name: scheduler-config