---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dynamic-memory-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dynamic-memory-controller
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["sscargal.com"]
    resources: ["dynamicmemories"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dynamic-memory-controller
subjects:
  - kind: ServiceAccount
    name: dynamic-memory-controller
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: dynamic-memory-controller
  apiGroup: rbac.authorization.k8s.io